{"ImportFile":"modules/input/python/2_logdir/bundle.tar","SourceModuleName":"in","SourceModuleType":"im_python","SyslogFacilityValue":16,"SyslogFacility":"LOCAL0","SyslogSeverityValue":7,"SyslogSeverity":"DEBUG","SeverityValue":1,"Severity":"DEBUG","Hostname":"logserve","EventTime":"2017-01-10 20:10:33","SourceName":"logwatcher","ProcessID":"601","Message":"Logging application bound to port"}
{"ImportFile":"modules/input/python/2_logdir/bundle.tar","SourceModuleName":"in","SourceModuleType":"im_python","SyslogFacilityValue":16,"SyslogFacility":"LOCAL0","SyslogSeverityValue":6,"SyslogSeverity":"INFO","SeverityValue":2,"Severity":"INFO","Hostname":"logserve","EventTime":"2017-01-10 20:10:34","SourceName":"logwatcher","ProcessID":"601","Message":"Logging application started and ready"}
{"ImportFile":"modules/input/python/2_logdir/bundle.tar","SourceModuleName":"in","SourceModuleType":"im_python","SyslogFacilityValue":16,"SyslogFacility":"LOCAL0","SyslogSeverityValue":1,"SyslogSeverity":"ALERT","SeverityValue":3,"Severity":"WARNING","Hostname":"logserve","EventTime":"2017-01-10 21:38:00","SourceName":"logwatcher","ProcessID":"601","Message":"Logging application failed"}
{"ImportFile":"modules/input/python/2_logdir/bundle.tar","SourceModuleName":"in","SourceModuleType":"im_python","SyslogFacilityValue":3,"SyslogFacility":"DAEMON","SyslogSeverityValue":4,"SyslogSeverity":"WARNING","SeverityValue":3,"Severity":"WARNING","Hostname":"nxubuntu","EventTime":"2017-01-10 21:40:38","SourceName":"atopacctd","ProcessID":"467","Message":"reactivate process accounting"}
{"ImportFile":"modules/input/python/2_logdir/bundle.tar","SourceModuleName":"in","SourceModuleType":"im_python","SyslogFacilityValue":3,"SyslogFacility":"DAEMON","SyslogSeverityValue":3,"SyslogSeverity":"ERR","SeverityValue":4,"Severity":"ERROR","Hostname":"nxubuntu","EventTime":"2017-01-10 21:40:38","SourceName":"atopacctd","ProcessID":"467","Message":"Retrying to switch on process accounting"}
{"ImportFile":"modules/input/python/2_logdir/bundle.tar","SourceModuleName":"in","SourceModuleType":"im_python","SyslogFacilityValue":3,"SyslogFacility":"DAEMON","SyslogSeverityValue":3,"SyslogSeverity":"ERR","SeverityValue":4,"Severity":"ERROR","Hostname":"nxubuntu","EventTime":"2017-01-10 21:40:38","SourceName":"atopacctd","ProcessID":"467","Message":"(see ATOP README about kernel bug 190271)"}
